# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xSEB-LTxWfHKEcSPO-ssMhSYhVC92y4a
"""

def calculate_bonus(base_salary , performance_rating):
  if performance_rating == 5 :
    bonus_amount = base_salary * 0.2
  elif performance_rating ==3 or performance_rating ==4 :
    bonus_amount = base_salary * 0.1
  else:
    bonus_amount = 0
  return bonus_amount

def calculate_tax (gross_salary):
  if gross_salary > 7000 :
    tax_percentage = 0.15
  elif gross_salary > 3000 and gross_salary < 7000 :
    tax_percentage = 0.10
  else :
    tax_percentage = 0
  return tax_percentage * gross_salary

def validation(performance_rating , base_salary):
  while performance_rating < 1 or performance_rating > 5:
    print ("Invalid Performance rating")
    performanceRating = input("Please enter valid performance rating (from 1 to 5) : ")
  while base_salary < 0 :
    print ("Invalid Base salary ")
    performanceRating = input("Please enter valid base salary (> 0) : ")

def display(name , base_salary , bonus_amount , tax_amount , net_salary ):
  print("\n" + '='*60)
  print(f"\t \t Payroll System for : {name}  ")
  print("\n" + '='*60)
  print(f"Base Salary : {base_salary : .2f} EGP")
  print(f"Earned Bonus : {bonus_amount : .2f} EGP")
  print(f"Tax Deduction : {tax_amount : .2f} EGP")
  print('-'*60)
  print(f"Net payable cash : {net_salary : .2f} EGP")

def main_hr_app():
  print("\t \t ---  Corporate Payroll System ---")

  name = input(f"Enter Employee Name : ")
  dept = input(f"Enter Employee Department : ")
  base_salary = float(input(f"Enter Employee Base Salary : "))
  performance_rating = int(input(f"Enter Employee Performance rating : "))

  validation(performance_rating , base_salary)

  bonus_amount = calculate_bonus(base_salary , performance_rating)
  gross_salary = bonus_amount + base_salary

  tax_amount = calculate_tax (gross_salary)
  net_salary = gross_salary - tax_amount

  display(name , base_salary , bonus_amount , tax_amount , net_salary )

main_hr_app()